### ISSUE TITLE
docstring indentation bug in gen_nodemap.py

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-node-manager#36]
The function docstrings in `gen_nodemap.py` are not indented correctly - see for example https://github.com/ESGF/esgf-node-manager/blob/7e0f34aeea9d198187b23c7641217be26e771346/src/python/server/gen_nodemap.py#L10-L20 The containing quote marks need to be indented to the same level as the code inside the function. Currently the module cannot be imported.

**Comment by sashakames** [comment]
Merged PR but the file is now deprecated and scheduled for removal from node manager installaion
